/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.93
 * Generated at: 2023-11-26 05:16:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.servlet.http.*;
import javax.servlet.*;

public final class settings_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Settings Page</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <a href=\"http://localhost:8080/SOT/index.jsp\"><H1>Home</H1></a>\r\n");
      out.write("    <h3>Create Organization</h3>\r\n");
      out.write("    <form action=\"settings.jsp\" method=\"post\"> \r\n");
      out.write("        <p>Please fill in this form to create an organization.</p>\r\n");
      out.write("\r\n");
      out.write("        <label for=\"orgName\"><b>Organization Name</b></label>\r\n");
      out.write("        <input type=\"text\" placeholder=\"Enter Organization Name\" name=\"orgName\" id=\"orgName\" required>\r\n");
      out.write("\r\n");
      out.write("        <label for=\"orgType\"><b>Organization Type</b></label>\r\n");
      out.write("        <select name=\"orgType\" id=\"orgType\" required>\r\n");
      out.write("            <option value=\"company\">Company</option>\r\n");
      out.write("            <option value=\"student\">Student</option>\r\n");
      out.write("        </select>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"schoolNameContainer\" style=\"display:none;\">\r\n");
      out.write("            <label for=\"schoolName\"><b>School Name</b></label>\r\n");
      out.write("            <input type=\"text\" placeholder=\"Enter School Name\" name=\"schoolName\" id=\"schoolName\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <button type=\"submit\" class=\"createOrgBtn\">Create Organization</button>\r\n");
      out.write("    </form>\r\n");
      out.write("    <h3>Create Team</h3>\r\n");
      out.write("    <form action=\"settings.jsp\" method=\"post\">\r\n");
      out.write("        <label for=\"teamName\"><b>Team Name</b></label>\r\n");
      out.write("        <input type=\"text\" placeholder=\"Enter Team Name\" name=\"teamName\" id=\"teamName\" required>\r\n");
      out.write("\r\n");
      out.write("        <button type=\"submit\" class=\"createTeamBtn\">Create Team</button>\r\n");
      out.write("    </form>\r\n");
      out.write("    <h3>Create Post</h3>\r\n");
      out.write("    <form action=\"settings.jsp\" method=\"post\">\r\n");
      out.write("        <label for=\"postContent\"><b>Post Content</b></label>\r\n");
      out.write("        <textarea name=\"postContent\" id=\"postContent\" required></textarea>\r\n");
      out.write("\r\n");
      out.write("        <button type=\"submit\" class=\"createPostBtn\">Create Post</button>\r\n");
      out.write("    </form>\r\n");
      out.write("    <h3>Create Event</h3>\r\n");
      out.write("    <form action=\"settings.jsp\" method=\"post\">\r\n");
      out.write("        <label for=\"eventName\"><b>Event Name</b></label>\r\n");
      out.write("        <input type=\"text\" placeholder=\"Enter Event Name\" name=\"eventName\" id=\"eventName\" required>\r\n");
      out.write("\r\n");
      out.write("        <label for=\"eventDate\"><b>Event Date</b></label>\r\n");
      out.write("        <input type=\"date\" name=\"eventDate\" id=\"eventDate\" required>\r\n");
      out.write("\r\n");
      out.write("        <button type=\"submit\" class=\"createEventBtn\">Create Event</button>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

        String orgType = request.getParameter("orgType");
        String schoolName = request.getParameter("schoolName");
        String teamName = request.getParameter("teamName");
        String postContent = request.getParameter("postContent");
        String eventName = request.getParameter("eventName");
        String eventDate = request.getParameter("eventDate");
        String orgName = request.getParameter("orgName");

        if (orgName == null || orgName.isEmpty()) {
          orgName = "SJSUACM"; 
        }

        String dbURL = "jdbc:mysql://localhost:3306/sot?autoReconnect=true&useSSL=false";
        String user = "root";
        String password = "1723";
        Connection con = null;
        PreparedStatement pstmt = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(dbURL, user, password);

            if(orgName != null && orgType != null) {
                String sql = "";
                if("student".equals(orgType)) {
                    sql = "INSERT INTO studentorg (OrgName, SchoolName) VALUES (?, ?)";
                    pstmt = con.prepareStatement(sql);
                    pstmt.setString(1, orgName);
                    pstmt.setString(2, schoolName);
                } else if("company".equals(orgType)) {
                    sql = "INSERT INTO companyorg (OrgName) VALUES (?)";
                    pstmt = con.prepareStatement(sql);
                    pstmt.setString(1, orgName);
                }
                int rowsAffected = pstmt.executeUpdate();
                if(rowsAffected > 0) {
                    out.println("<p>Organization created successfully</p>");
                } else {
                    out.println("<p>An error occurred</p>");
                }
            }

            if(teamName != null && !teamName.isEmpty()) {
                String sql = "INSERT INTO teams (TeamName, Orgname) VALUES (?, ?)";
                pstmt = con.prepareStatement(sql);
                pstmt.setString(1, teamName);
                pstmt.setString(2, orgName);
                int rowsAffected = pstmt.executeUpdate();
                if(rowsAffected > 0) {
                    out.println("<p>Team created successfully</p>");
                } else {
                    out.println("<p>An error occurred while creating the team</p>");
                }
            }

            if(postContent != null && !postContent.trim().isEmpty()) {
            
                String sql = "INSERT INTO posts (body) VALUES (?)";
                pstmt = con.prepareStatement(sql);
                pstmt.setString(1, postContent);
            
                int rowsAffected = pstmt.executeUpdate();
                if(rowsAffected > 0) {
                    out.println("<p>Post created successfully</p>");
                } else {
                    out.println("<p>An error occurred while creating the post</p>");
                }
            }

            if(eventName != null && eventDate != null && !eventName.trim().isEmpty() && !eventDate.trim().isEmpty()) {
                boolean isAdmin = true; // FIXME: check actual admin 
                boolean isStudentOrgAdmin = true; // FIXME: check if admin is of student org
            
                if(isAdmin && isStudentOrgAdmin) {
                    String sql = "INSERT INTO events (eventname, eventdate, orgname) VALUES (?, ?, ?)";
                    pstmt = con.prepareStatement(sql);
                    pstmt.setString(1, eventName);
                    pstmt.setDate(2, java.sql.Date.valueOf(eventDate));
                    pstmt.setString(3, orgName); 
            
                    int rowsAffected = pstmt.executeUpdate();
                    if(rowsAffected > 0) {
                        out.println("<p>Event created successfully</p>");
                    } else {
                        out.println("<p>Error occurred while creating the event</p>");
                    }
                } else {
                    out.println("<p>Only administrators of student organizations can create events.</p>");
                }
            }

        } catch(SQLException e) {
            out.println("<p>SQLException caught: " + e.getMessage() + "</p>");
        } catch(ClassNotFoundException e) {
            out.println("<p>ClassNotFoundException caught: " + e.getMessage() + "</p>");
        } finally {
            if(pstmt != null) {
                try {
                    pstmt.close();
                } catch(SQLException e) {
                    out.println("<p>Error closing PreparedStatement: " + e.getMessage() + "</p>");
                }
            }
            if(con != null) {
                try {
                    con.close();
                } catch(SQLException e) {
                    out.println("<p>Error closing Connection: " + e.getMessage() + "</p>");
                }
            }
        }
    
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
